name: Run Tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull enigmampc/secret-network-sw-dev:v1.2.2-1
      # - name: Docker Layer Caching
      #   uses: satackey/action-docker-layer-caching@v0.0.11
      - run: yarn
      - run: yarn test
