name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install npm dependencies
        run: yarn
      - name: Run tests
        env:
          SKIP_LOCALSECRET: false
        run: yarn test

  Tests-CW20-IBC:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
        #      - name: "Pull docker testnet image"
        #        run: docker pull ghcr.io/scrtlabs/localsecret:v1.6.0-alpha.4
      - name: Install npm dependencies
        run: |
          cd test/cw20-ics20 && yarn
      - name: Run tests
        run: |
          cd test/cw20-ics20
          docker compose -f ./docker-compose.yml up -d
          npx jest --forceExit
