name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: "Pull docker testnet image"
        run: docker pull enigmampc/secret-network-sw-dev:v1.2.2-1
      - name: Install npm dependencies
        run: yarn
      - name: Run tests
        run: yarn test
